Update buildspec.yml

diff --git a/buildspec.yml b/buildspec.yml
--- a/buildspec.yml
+++ b/buildspec.yml
@@ -15,14 +15,20 @@ phases:
     commands:
       - echo AWS CLI is already installed in the standard image
       - echo Maven is already installed in the standard image
-      - echo Installing SonarQube Scanner...
-      - curl -sSLo sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.7.0.2747-linux.zip
-      - unzip sonar-scanner.zip
-      - export PATH=$PATH:$PWD/sonar-scanner-4.7.0.2747-linux/bin
-      - sonar-scanner --version
+      
 
   pre_build:
     commands:
+      - echo "pre-build started
+      - pwd
+      - ls -lrt
+      - echo "Code Scanning..."
+      - mvn clean verify sonar:sonar
+      - pwd
+      - ls -lrt 
+      - echo "Code Scanning has been completed!"
+      - echo Cleaning the project...
+      - mvn clean
       - echo Validating project...
       - mvn validate
       - echo Compiling the project...
@@ -47,7 +53,20 @@ phases:
   post_build:
     commands:
       - echo Checking SonarQube quality gate status...
-      - curl -u $SONARQUBE_TOKEN:"$SONARQUBE_SERVER/api/qualitygates/project_status?projectKey=$SONARQUBE_PROJECT_KEY" | jq '.projectStatus.status'
+      - |
+      # Check the quality gate status
+      response=$(curl -s -u $SONARQUBE_TOKEN: "$SONARQUBE_SERVER/api/qualitygates/project_status?projectKey=$SONARQUBE_PROJECT_KEY")
+      status=$(echo $response | jq -r '.projectStatus.status')
+
+      # Output the status
+      echo "Quality gate status: $status"
+
+      # Abort the build if the quality gate status is not OK
+      if [ "$status" != "OK" ]; then
+        echo "Pipeline aborted due to quality gate failure: $status"
+        exit 1
+      fi
+
       - echo Deploying the WAR file to Tomcat...
       - aws s3 cp s3://$S3_BUCKET/artifacts/*.war /opt/tom/temp/
       - sudo mv /opt/tomcat/temp/*.war /opt/tomcat/webapps/
